from typing import List


NUTRITION_CATALOG = [
    # -------------------- BREAKFAST --------------------
    {
        "id": 1,
        "name": "Овсянка с бананом и орехами",
        "calories": 520,
        "protein": 18,
        "fat": 16,
        "carbs": 74,
        "meal_slots": ["breakfast"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["nuts", "gluten"],
        "recipe": "Свари овсянку, добавь банан и немного орехов.",
    },
    {
        "id": 2,
        "name": "Омлет с овощами",
        "calories": 290,
        "protein": 24,
        "fat": 16,
        "carbs": 10,
        "meal_slots": ["breakfast", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["eggs"],
        "recipe": "Приготовь омлет с овощами на сковороде.",
    },
    {
        "id": 3,
        "name": "Творог с ягодами",
        "calories": 240,
        "protein": 22,
        "fat": 7,
        "carbs": 16,
        "meal_slots": ["breakfast", "snack", "dinner", "late"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "quick_meals"],
        "allergens": ["milk"],
        "recipe": "Смешай творог с ягодами без сахара.",
    },
    {
        "id": 4,
        "name": "Греческий йогурт с гранолой",
        "calories": 360,
        "protein": 20,
        "fat": 8,
        "carbs": 46,
        "meal_slots": ["breakfast", "snack"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced", "quick_meals"],
        "allergens": ["milk", "gluten"],
        "recipe": "Смешай греческий йогурт и гранолу.",
    },
    {
        "id": 5,
        "name": "Овсянка с яблоком и корицей",
        "calories": 310,
        "protein": 10,
        "fat": 6,
        "carbs": 56,
        "meal_slots": ["breakfast"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced", "no_sugar"],
        "allergens": ["gluten"],
        "recipe": "Свари овсянку и добавь яблоко с корицей.",
    },
    {
        "id": 6,
        "name": "Яичница с цельнозерновым хлебом",
        "calories": 340,
        "protein": 19,
        "fat": 17,
        "carbs": 24,
        "meal_slots": ["breakfast"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": ["eggs", "gluten"],
        "recipe": "Пожарь яйца и подай с цельнозерновым хлебом.",
    },
    {
        "id": 7,
        "name": "Сырники без сахара",
        "calories": 330,
        "protein": 22,
        "fat": 12,
        "carbs": 30,
        "meal_slots": ["breakfast", "snack"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["high_protein"],
        "allergens": ["milk", "eggs", "gluten"],
        "recipe": "Сделай сырники из творога и подай без сахара.",
    },
    {
        "id": 8,
        "name": "Тост с авокадо и яйцом",
        "calories": 370,
        "protein": 16,
        "fat": 20,
        "carbs": 28,
        "meal_slots": ["breakfast"],
        "goal_tags": ["keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["eggs", "gluten"],
        "recipe": "Поджарь хлеб, добавь авокадо и вареное яйцо.",
    },
    {
        "id": 9,
        "name": "Пшенная каша с тыквой",
        "calories": 290,
        "protein": 8,
        "fat": 5,
        "carbs": 54,
        "meal_slots": ["breakfast"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Свари пшено с кусочками тыквы.",
    },
    {
        "id": 10,
        "name": "Омлет с сыром",
        "calories": 410,
        "protein": 26,
        "fat": 28,
        "carbs": 6,
        "meal_slots": ["breakfast"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["eggs", "milk"],
        "recipe": "Приготовь омлет и добавь тертый сыр.",
    },
    {
        "id": 11,
        "name": "Рисовая каша с молоком",
        "calories": 340,
        "protein": 9,
        "fat": 7,
        "carbs": 60,
        "meal_slots": ["breakfast"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["milk"],
        "recipe": "Свари рисовую кашу на молоке.",
    },
    {
        "id": 12,
        "name": "Йогурт с бананом и семенами",
        "calories": 300,
        "protein": 14,
        "fat": 8,
        "carbs": 40,
        "meal_slots": ["breakfast", "snack"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["quick_meals", "balanced"],
        "allergens": ["milk"],
        "recipe": "Смешай йогурт, банан и семена.",
    },
    {
        "id": 13,
        "name": "Творог с медом и орехами",
        "calories": 430,
        "protein": 27,
        "fat": 16,
        "carbs": 34,
        "meal_slots": ["breakfast", "snack"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["high_protein"],
        "allergens": ["milk", "nuts"],
        "recipe": "Добавь к творогу немного меда и орехов.",
    },
    {
        "id": 14,
        "name": "Гречневая каша с яйцом",
        "calories": 350,
        "protein": 16,
        "fat": 12,
        "carbs": 38,
        "meal_slots": ["breakfast"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced", "high_protein"],
        "allergens": ["eggs"],
        "recipe": "Отвари гречку и подай с вареным яйцом.",
    },

    # -------------------- LUNCH / DINNER --------------------
    {
        "id": 15,
        "name": "Рис с курицей",
        "calories": 680,
        "protein": 42,
        "fat": 14,
        "carbs": 88,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass"],
        "preference_tags": ["balanced", "high_protein"],
        "allergens": [],
        "recipe": "Отвари рис и добавь приготовленную курицу.",
    },
    {
        "id": 16,
        "name": "Гречка с индейкой",
        "calories": 340,
        "protein": 30,
        "fat": 9,
        "carbs": 28,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["balanced", "high_protein"],
        "allergens": [],
        "recipe": "Отвари гречку и подай с индейкой.",
    },
    {
        "id": 17,
        "name": "Макароны с говядиной",
        "calories": 710,
        "protein": 36,
        "fat": 18,
        "carbs": 90,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": ["gluten"],
        "recipe": "Отвари макароны и смешай с говядиной.",
    },
    {
        "id": 18,
        "name": "Салат с тунцом",
        "calories": 320,
        "protein": 28,
        "fat": 12,
        "carbs": 14,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["fish"],
        "recipe": "Смешай листья салата, овощи и тунец.",
    },
    {
        "id": 19,
        "name": "Лосось с овощами",
        "calories": 370,
        "protein": 31,
        "fat": 16,
        "carbs": 14,
        "meal_slots": ["dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["fish"],
        "recipe": "Запеки лосось и подай с овощами.",
    },
    {
        "id": 20,
        "name": "Картофель с индейкой",
        "calories": 620,
        "protein": 38,
        "fat": 16,
        "carbs": 72,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Запеки картофель и индейку в духовке.",
    },
    {
        "id": 21,
        "name": "Куриная грудка с брокколи",
        "calories": 300,
        "protein": 35,
        "fat": 9,
        "carbs": 12,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": [],
        "recipe": "Обжарь или запеки куриную грудку и подай с брокколи.",
    },
    {
        "id": 22,
        "name": "Булгур с курицей",
        "calories": 460,
        "protein": 30,
        "fat": 10,
        "carbs": 56,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": ["gluten"],
        "recipe": "Отвари булгур и подай с курицей.",
    },
    {
        "id": 23,
        "name": "Плов с говядиной",
        "calories": 730,
        "protein": 32,
        "fat": 22,
        "carbs": 94,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Приготовь плов с рисом и говядиной.",
    },
    {
        "id": 24,
        "name": "Коричневый рис с овощами и курицей",
        "calories": 430,
        "protein": 29,
        "fat": 9,
        "carbs": 54,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Смешай коричневый рис, овощи и курицу.",
    },
    {
        "id": 25,
        "name": "Филе индейки с киноа",
        "calories": 410,
        "protein": 33,
        "fat": 10,
        "carbs": 42,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["high_protein", "balanced"],
        "allergens": [],
        "recipe": "Запеки индейку и подай с киноа.",
    },
    {
        "id": 26,
        "name": "Чечевица с курицей",
        "calories": 420,
        "protein": 32,
        "fat": 9,
        "carbs": 48,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["high_protein", "balanced"],
        "allergens": [],
        "recipe": "Свари чечевицу и подай с курицей.",
    },
    {
        "id": 27,
        "name": "Тушеная говядина с картофелем",
        "calories": 590,
        "protein": 34,
        "fat": 18,
        "carbs": 58,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Потуши говядину и картофель вместе.",
    },
    {
        "id": 28,
        "name": "Рыба с гречкой",
        "calories": 390,
        "protein": 29,
        "fat": 10,
        "carbs": 34,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["high_protein", "balanced"],
        "allergens": ["fish"],
        "recipe": "Запеки рыбу и подай с гречкой.",
    },
    {
        "id": 29,
        "name": "Паста с курицей и томатным соусом",
        "calories": 640,
        "protein": 34,
        "fat": 12,
        "carbs": 86,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["gluten"],
        "recipe": "Смешай пасту, курицу и томатный соус.",
    },
    {
        "id": 30,
        "name": "Курица с салатом",
        "calories": 360,
        "protein": 35,
        "fat": 12,
        "carbs": 14,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": [],
        "recipe": "Запеки курицу и подай с овощным салатом.",
    },
    {
        "id": 31,
        "name": "Запеченная треска с овощами",
        "calories": 290,
        "protein": 30,
        "fat": 8,
        "carbs": 12,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["fish"],
        "recipe": "Запеки треску и овощи в духовке.",
    },
    {
        "id": 32,
        "name": "Котлеты из индейки с рисом",
        "calories": 470,
        "protein": 32,
        "fat": 13,
        "carbs": 50,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": ["eggs"],
        "recipe": "Приготовь котлеты из индейки и подай с рисом.",
    },
    {
        "id": 33,
        "name": "Курица терияки с рисом",
        "calories": 610,
        "protein": 31,
        "fat": 14,
        "carbs": 84,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Приготовь курицу терияки и подай с рисом.",
    },
    {
        "id": 34,
        "name": "Рагу из индейки и овощей",
        "calories": 350,
        "protein": 29,
        "fat": 11,
        "carbs": 20,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": [],
        "recipe": "Потуши индейку и овощи.",
    },
    {
        "id": 35,
        "name": "Чечевичный суп с курицей",
        "calories": 340,
        "protein": 24,
        "fat": 8,
        "carbs": 36,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Приготовь чечевичный суп и добавь курицу.",
    },
    {
        "id": 36,
        "name": "Овощной суп с говядиной",
        "calories": 380,
        "protein": 25,
        "fat": 12,
        "carbs": 26,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": [],
        "recipe": "Свари овощной суп и добавь кусочки говядины.",
    },
    {
        "id": 37,
        "name": "Говядина с булгуром",
        "calories": 570,
        "protein": 33,
        "fat": 17,
        "carbs": 62,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["gluten"],
        "recipe": "Обжарь говядину и подай с булгуром.",
    },
    {
        "id": 38,
        "name": "Курица карри с рисом",
        "calories": 560,
        "protein": 31,
        "fat": 15,
        "carbs": 70,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["balanced"],
        "allergens": ["milk"],
        "recipe": "Приготовь курицу карри и подай с рисом.",
    },
    {
        "id": 39,
        "name": "Запеченная скумбрия с овощами",
        "calories": 410,
        "protein": 28,
        "fat": 23,
        "carbs": 10,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["fish"],
        "recipe": "Запеки скумбрию с овощами.",
    },
    {
        "id": 40,
        "name": "Фасоль с индейкой",
        "calories": 450,
        "protein": 31,
        "fat": 11,
        "carbs": 48,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced", "high_protein"],
        "allergens": [],
        "recipe": "Потуши фасоль с индейкой.",
    },
    {
        "id": 41,
        "name": "Куриная грудка с киноа и овощами",
        "calories": 430,
        "protein": 34,
        "fat": 9,
        "carbs": 42,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced", "high_protein"],
        "allergens": [],
        "recipe": "Запеки курицу и подай с киноа и овощами.",
    },
    {
        "id": 42,
        "name": "Рис с омлетом и овощами",
        "calories": 480,
        "protein": 22,
        "fat": 13,
        "carbs": 62,
        "meal_slots": ["lunch", "dinner"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["balanced"],
        "allergens": ["eggs"],
        "recipe": "Сделай рис, омлет и добавь овощи.",
    },

    # -------------------- SNACK --------------------
    {
        "id": 43,
        "name": "Йогурт и яблоко",
        "calories": 180,
        "protein": 10,
        "fat": 5,
        "carbs": 22,
        "meal_slots": ["snack", "late"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["quick_meals", "no_sugar"],
        "allergens": ["milk"],
        "recipe": "Возьми натуральный йогурт и яблоко.",
    },
    {
        "id": 44,
        "name": "Бутерброд с арахисовой пастой и бананом",
        "calories": 430,
        "protein": 14,
        "fat": 18,
        "carbs": 54,
        "meal_slots": ["snack", "breakfast"],
        "goal_tags": ["gain_mass"],
        "preference_tags": ["quick_meals"],
        "allergens": ["nuts", "gluten"],
        "recipe": "Намажь арахисовую пасту на хлеб и добавь банан.",
    },
    {
        "id": 45,
        "name": "Кефир и хлебцы",
        "calories": 210,
        "protein": 12,
        "fat": 5,
        "carbs": 24,
        "meal_slots": ["late", "snack"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["quick_meals"],
        "allergens": ["milk", "gluten"],
        "recipe": "Добавь к кефиру 2–3 хлебца.",
    },
    {
        "id": 46,
        "name": "Протеиновый коктейль",
        "calories": 260,
        "protein": 28,
        "fat": 6,
        "carbs": 20,
        "meal_slots": ["snack", "late"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["high_protein", "quick_meals"],
        "allergens": ["milk"],
        "recipe": "Смешай протеин с молоком или водой.",
    },
    {
        "id": 47,
        "name": "Орехи и сухофрукты",
        "calories": 390,
        "protein": 10,
        "fat": 20,
        "carbs": 40,
        "meal_slots": ["snack"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["quick_meals"],
        "allergens": ["nuts"],
        "recipe": "Смешай орехи и немного сухофруктов.",
    },
    {
        "id": 48,
        "name": "Творожный мусс",
        "calories": 230,
        "protein": 20,
        "fat": 7,
        "carbs": 18,
        "meal_slots": ["snack", "late"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein"],
        "allergens": ["milk"],
        "recipe": "Взбей творог до мягкой текстуры.",
    },
    {
        "id": 49,
        "name": "Смузи с бананом и йогуртом",
        "calories": 320,
        "protein": 14,
        "fat": 6,
        "carbs": 52,
        "meal_slots": ["snack"],
        "goal_tags": ["gain_mass", "keep_fit"],
        "preference_tags": ["quick_meals"],
        "allergens": ["milk"],
        "recipe": "Взбей банан и йогурт в блендере.",
    },
    {
        "id": 50,
        "name": "Хумус с овощными палочками",
        "calories": 240,
        "protein": 9,
        "fat": 11,
        "carbs": 24,
        "meal_slots": ["snack"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["balanced", "vegetarian"],
        "allergens": [],
        "recipe": "Подавай хумус с морковью и огурцом.",
    },
    {
        "id": 51,
        "name": "Сэндвич с индейкой",
        "calories": 350,
        "protein": 22,
        "fat": 9,
        "carbs": 38,
        "meal_slots": ["snack", "lunch"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["quick_meals", "balanced"],
        "allergens": ["gluten"],
        "recipe": "Сделай сэндвич с индейкой и овощами.",
    },
    {
        "id": 52,
        "name": "Яблоко и арахисовая паста",
        "calories": 260,
        "protein": 8,
        "fat": 14,
        "carbs": 24,
        "meal_slots": ["snack"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["quick_meals"],
        "allergens": ["nuts"],
        "recipe": "Нарежь яблоко и добавь немного арахисовой пасты.",
    },
    {
        "id": 53,
        "name": "Банан и творог",
        "calories": 280,
        "protein": 18,
        "fat": 5,
        "carbs": 36,
        "meal_slots": ["snack"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["high_protein", "quick_meals"],
        "allergens": ["milk"],
        "recipe": "Смешай творог и кусочки банана.",
    },
    {
        "id": 54,
        "name": "Протеиновый батончик",
        "calories": 250,
        "protein": 20,
        "fat": 8,
        "carbs": 24,
        "meal_slots": ["snack"],
        "goal_tags": ["keep_fit", "gain_mass"],
        "preference_tags": ["quick_meals", "high_protein"],
        "allergens": ["milk", "nuts", "gluten"],
        "recipe": "Возьми готовый протеиновый батончик.",
    },
    {
        "id": 55,
        "name": "Груша и греческий йогурт",
        "calories": 210,
        "protein": 13,
        "fat": 4,
        "carbs": 28,
        "meal_slots": ["snack"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["quick_meals", "balanced"],
        "allergens": ["milk"],
        "recipe": "Подавай грушу с греческим йогуртом.",
    },
    {
        "id": 56,
        "name": "Хлебцы с творожным сыром",
        "calories": 220,
        "protein": 11,
        "fat": 8,
        "carbs": 24,
        "meal_slots": ["snack"],
        "goal_tags": ["keep_fit", "lose_weight"],
        "preference_tags": ["quick_meals"],
        "allergens": ["milk", "gluten"],
        "recipe": "Намажь творожный сыр на хлебцы.",
    },

    # -------------------- LATE / LIGHT DINNER --------------------
    {
        "id": 57,
        "name": "Кефир перед сном",
        "calories": 120,
        "protein": 8,
        "fat": 3,
        "carbs": 10,
        "meal_slots": ["late"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["quick_meals", "no_sugar"],
        "allergens": ["milk"],
        "recipe": "Выпей стакан кефира.",
    },
    {
        "id": 58,
        "name": "Творог перед сном",
        "calories": 170,
        "protein": 22,
        "fat": 4,
        "carbs": 6,
        "meal_slots": ["late"],
        "goal_tags": ["keep_fit", "lose_weight", "gain_mass"],
        "preference_tags": ["high_protein", "quick_meals", "low_carb"],
        "allergens": ["milk"],
        "recipe": "Съешь порцию творога без сахара.",
    },
    {
        "id": 59,
        "name": "Омлет из белков",
        "calories": 160,
        "protein": 22,
        "fat": 4,
        "carbs": 4,
        "meal_slots": ["late", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["eggs"],
        "recipe": "Сделай легкий омлет из яичных белков.",
    },
    {
        "id": 60,
        "name": "Йогурт без сахара",
        "calories": 140,
        "protein": 10,
        "fat": 4,
        "carbs": 12,
        "meal_slots": ["late", "snack"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["quick_meals", "no_sugar"],
        "allergens": ["milk"],
        "recipe": "Возьми натуральный йогурт без сахара.",
    },
    {
        "id": 61,
        "name": "Легкий салат с курицей",
        "calories": 250,
        "protein": 24,
        "fat": 9,
        "carbs": 10,
        "meal_slots": ["late", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": [],
        "recipe": "Смешай овощи и кусочки курицы.",
    },
    {
        "id": 62,
        "name": "Творог с корицей",
        "calories": 180,
        "protein": 22,
        "fat": 5,
        "carbs": 8,
        "meal_slots": ["late"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["high_protein", "low_carb"],
        "allergens": ["milk"],
        "recipe": "Добавь немного корицы в творог.",
    },
    {
        "id": 63,
        "name": "Куриный бульон",
        "calories": 90,
        "protein": 10,
        "fat": 4,
        "carbs": 3,
        "meal_slots": ["late", "dinner"],
        "goal_tags": ["lose_weight", "keep_fit"],
        "preference_tags": ["quick_meals", "low_carb"],
        "allergens": [],
        "recipe": "Подогрей легкий куриный бульон.",
    },
    {
        "id": 64,
        "name": "Яйца вкрутую",
        "calories": 160,
        "protein": 13,
        "fat": 11,
        "carbs": 1,
        "meal_slots": ["late", "snack", "breakfast"],
        "goal_tags": ["keep_fit", "lose_weight", "gain_mass"],
        "preference_tags": ["high_protein", "quick_meals", "low_carb"],
        "allergens": ["eggs"],
        "recipe": "Отвари яйца вкрутую.",
    },
]


def parse_csv(value: str | None) -> List[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


def get_current_meal_slot(hour: int) -> str:
    if hour < 11:
        return "breakfast"
    if hour < 16:
        return "lunch"
    if hour < 19:
        return "snack"
    if hour < 23:
        return "dinner"
    return "late"